set -g default-terminal screen-256color
set-option -ga update-environment 'CONDA_DEFAULT_ENV'

# vim key bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# switch between tmux windows
bind H previous-window
bind L next-window

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Automatically restore the last saved tmux environment
set -g @continuum-restore 'on'


# Bootstrap TPM install
if "test ! -d ~/.tmux/plugins/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
